name: Build Windows EXE

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.4'  # Set to your Flutter version

      - name: Install Dependencies
        run: flutter pub get

      - name: Build Windows Executable
        run: flutter build windows

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: windows-exe
          path: build/windows/runner/Release/*.exe
